_ID3_TAG_MAP = {
    '_rating': {
        "name": 'Rating',
        "ID3v2": 'POPM',
        "Vorbis": 'RATING:user@email',
        "APEv2": None,
        "iTunes": None,
        "ASF": 'WM/SharedUserRating',
        "RIFF": None,
    },
    'acoustid_fingerprint': {
        "name": 'AcoustID Fingerprint',
        "ID3v2": 'TXXX:Acoustid Fingerprint',
        "Vorbis": 'ACOUSTID_FINGERPRINT',
        "APEv2": 'Acoustid_Fingerprint',
        "iTunes": '----:com.apple.iTunes:Acoustid Fingerprint',
        "ASF": 'Acoustid/Fingerprint',
        "RIFF": None,
    },
    'acoustid_id': {
        "name": 'AcoustID',
        "ID3v2": 'TXXX:Acoustid Id',
        "Vorbis": 'ACOUSTID_ID',
        "APEv2": 'Acoustid_Id',
        "iTunes": '----:com.apple.iTunes:Acoustid Id',
        "ASF": 'Acoustid/Id',
        "RIFF": None,
    },
    'album': {
        "name": 'Album',
        "ID3v2": 'TALB',
        "Vorbis": 'ALBUM',
        "APEv2": 'Album',
        "iTunes": '©alb',
        "ASF": 'WM/AlbumTitle',
        "RIFF": 'IPRD',
    },
    'albumartist': {
        "name": 'Album Artist',
        "ID3v2": 'TPE2',
        "Vorbis": 'ALBUMARTIST',
        "APEv2": 'Album Artist',
        "iTunes": 'aART',
        "ASF": 'WM/AlbumArtist',
        "RIFF": None,
    },
    'albumartists': {
        "name": 'Album Artists',
        "ID3v2": 'TXXX:ALBUMARTISTS',
        "Vorbis": 'ALBUMARTISTS',
        "APEv2": 'ALBUMARTISTS',
        "iTunes": '----:com.apple.iTunes:ALBUMARTISTS',
        "ASF": 'WM/ALBUMARTISTS',
        "RIFF": None,
    },
    'albumartistsort': {
        "name": 'Album Artist Sort Order',
        "ID3v2": 'TSO2 (Picard>=1.2)\nTXXX:ALBUMARTISTSORT (Picard<=1.1)',
        "Vorbis": 'ALBUMARTISTSORT',
        "APEv2": 'Albumartistsort',
        "iTunes": 'soaa',
        "ASF": 'WM/AlbumArtistSortOrder',
        "RIFF": None,
    },
    'albumsort': {
        "name": 'Album Sort Order [4]',
        "ID3v2": 'TSOA',
        "Vorbis": 'ALBUMSORT',
        "APEv2": 'Albumsort',
        "iTunes": 'soal',
        "ASF": 'WM/AlbumSortOrder',
        "RIFF": None,
    },
    'arranger': {
        "name": 'Arranger',
        "ID3v2": 'TIPL:arranger (ID3v2.4)\nIPLS:arranger (ID3v2.3)',
        "Vorbis": 'ARRANGER',
        "APEv2": 'Arranger',
        "iTunes": None,
        "ASF": None,
        "RIFF": None,
    },
    'artist': {
        "name": 'Artist',
        "ID3v2": 'TPE1',
        "Vorbis": 'ARTIST',
        "APEv2": 'Artist',
        "iTunes": '©ART',
        "ASF": 'Author',
        "RIFF": 'IART',
    },
    'artists': {
        "name": 'Artists',
        "ID3v2": 'TXXX:Artists',
        "Vorbis": 'ARTISTS',
        "APEv2": 'Artists',
        "iTunes": '----:com.apple.iTunes:ARTISTS',
        "ASF": 'WM/ARTISTS',
        "RIFF": None,
    },
    'artistsort': {
        "name": 'Artist Sort Order',
        "ID3v2": 'TSOP',
        "Vorbis": 'ARTISTSORT',
        "APEv2": 'Artistsort',
        "iTunes": 'soar',
        "ASF": 'WM/ArtistSortOrder',
        "RIFF": None,
    },
    'asin': {
        "name": 'ASIN',
        "ID3v2": 'TXXX:ASIN',
        "Vorbis": 'ASIN',
        "APEv2": 'Asin',
        "iTunes": '----:com.apple.iTunes:ASIN',
        "ASF": 'ASIN',
        "RIFF": None,
    },
    'barcode': {
        "name": 'Barcode',
        "ID3v2": 'TXXX:BARCODE',
        "Vorbis": 'BARCODE',
        "APEv2": 'Barcode',
        "iTunes": '----:com.apple.iTunes:BARCODE',
        "ASF": 'WM/Barcode',
        "RIFF": None,
    },
    'bpm': {
        "name": 'BPM [4]',
        "ID3v2": 'TBPM',
        "Vorbis": 'BPM',
        "APEv2": 'BPM',
        "iTunes": 'tmpo',
        "ASF": 'WM/BeatsPerMinute',
        "RIFF": None,
    },
    'catalognumber': {
        "name": 'Catalog Number',
        "ID3v2": 'TXXX:CATALOGNUMBER',
        "Vorbis": 'CATALOGNUMBER',
        "APEv2": 'CatalogNumber',
        "iTunes": '----:com.apple.iTunes:CATALOGNUMBER',
        "ASF": 'WM/CatalogNo',
        "RIFF": None,
    },
    'comment:description': {
        "name": 'Comment [4]',
        "ID3v2": 'COMM:description',
        "Vorbis": 'COMMENT',
        "APEv2": 'Comment',
        "iTunes": '©cmt',
        "ASF": 'Description',
        "RIFF": 'ICMT',
    },
    'compilation': {
        "name": 'Compilation (iTunes) [5]',
        "ID3v2": 'TCMP',
        "Vorbis": 'COMPILATION',
        "APEv2": 'Compilation',
        "iTunes": 'cpil',
        "ASF": 'WM/IsCompilation',
        "RIFF": None,
    },
    'composer': {
        "name": 'Composer',
        "ID3v2": 'TCOM',
        "Vorbis": 'COMPOSER',
        "APEv2": 'Composer',
        "iTunes": '©wrt',
        "ASF": 'WM/Composer',
        "RIFF": 'IMUS',
    },
    'composersort': {
        "name": 'Composer Sort Order',
        "ID3v2": 'TSOC (Picard>=1.3)\nTXXX:COMPOSERSORT (Picard<=1.2)',
        "Vorbis": 'COMPOSERSORT',
        "APEv2": 'Composersort',
        "iTunes": 'soco',
        "ASF": 'WM/ComposerSortOrder (Picard>=1.3)',
        "RIFF": None,
    },
    'conductor': {
        "name": 'Conductor',
        "ID3v2": 'TPE3',
        "Vorbis": 'CONDUCTOR',
        "APEv2": 'Conductor',
        "iTunes": '----:com.apple.iTunes:CONDUCTOR',
        "ASF": 'WM/Conductor',
        "RIFF": None,
    },
    'copyright': {
        "name": 'Copyright [4]',
        "ID3v2": 'TCOP',
        "Vorbis": 'COPYRIGHT',
        "APEv2": 'Copyright',
        "iTunes": 'cprt',
        "ASF": 'Copyright',
        "RIFF": 'ICOP',
    },
    'date': {
        "name": 'Release Date',
        "ID3v2": 'TDRC (ID3v2.4)\nTYER + TDAT (ID3v2.3)',
        "Vorbis": 'DATE',
        "APEv2": 'Year',
        "iTunes": '©day',
        "ASF": 'WM/Year',
        "RIFF": 'ICRD',
    },
    'director': {
        "name": 'Director',
        "ID3v2": 'TXXX:DIRECTOR',
        "Vorbis": 'DIRECTOR',
        "APEv2": 'Director',
        "iTunes": '©dir [9]',
        "ASF": 'WM/Director',
        "RIFF": None,
    },
    'discnumber': {
        "name": 'Disc Number',
        "ID3v2": 'TPOS',
        "Vorbis": 'DISCNUMBER',
        "APEv2": 'Disc',
        "iTunes": 'disk',
        "ASF": 'WM/PartOfSet',
        "RIFF": None,
    },
    'discsubtitle': {
        "name": 'Disc Subtitle',
        "ID3v2": 'TSST (ID3v2.4 only)',
        "Vorbis": 'DISCSUBTITLE',
        "APEv2": 'DiscSubtitle',
        "iTunes": '----:com.apple.iTunes:DISCSUBTITLE',
        "ASF": 'WM/SetSubTitle',
        "RIFF": None,
    },
    'djmixer': {
        "name": 'Mix-DJ',
        "ID3v2": 'TIPL:DJ-mix (ID3v2.4)\nIPLS:DJ-mix (ID3v2.3)',
        "Vorbis": 'DJMIXER',
        "APEv2": 'Djmixer',
        "iTunes": '----:com.apple.iTunes:DJMIXER',
        "ASF": 'WM/DJMixer',
        "RIFF": None,
    },
    'encodedby': {
        "name": 'Encoded By [4]',
        "ID3v2": 'TENC',
        "Vorbis": 'ENCODEDBY',
        "APEv2": 'EncodedBy',
        "iTunes": '©too',
        "ASF": 'WM/EncodedBy',
        "RIFF": 'IENC',
    },
    'encodersettings': {
        "name": 'Encoder Settings [4]',
        "ID3v2": 'TSSE',
        "Vorbis": 'ENCODERSETTINGS',
        "APEv2": 'Encodersettings',
        "iTunes": None,
        "ASF": 'WM/EncodingSettings (Picard>=1.3.1)',
        "RIFF": None,
    },
    'engineer': {
        "name": 'Engineer',
        "ID3v2": 'TIPL:engineer (ID3v2.4)\nIPLS:engineer (ID3v2.3)',
        "Vorbis": 'ENGINEER',
        "APEv2": 'Engineer',
        "iTunes": '----:com.apple.iTunes:ENGINEER',
        "ASF": 'WM/Engineer',
        "RIFF": 'IENG',
    },
    'gapless': {
        "name": 'Gapless Playback [4]',
        "ID3v2": None,
        "Vorbis": None,
        "APEv2": None,
        "iTunes": 'pgap',
        "ASF": None,
        "RIFF": None,
    },
    'genre': {
        "name": 'Genre',
        "ID3v2": 'TCON',
        "Vorbis": 'GENRE',
        "APEv2": 'Genre',
        "iTunes": '©gen',
        "ASF": 'WM/Genre',
        "RIFF": 'IGNR',
    },
    'grouping': {
        "name": 'Grouping [3]',
        "ID3v2": 'TIT1\nGRP1 [8]',
        "Vorbis": 'GROUPING',
        "APEv2": 'Grouping',
        "iTunes": '©grp',
        "ASF": 'WM/ContentGroupDescription',
        "RIFF": None,
    },
    'isrc': {
        "name": 'ISRC',
        "ID3v2": 'TSRC',
        "Vorbis": 'ISRC',
        "APEv2": 'ISRC',
        "iTunes": '----:com.apple.iTunes:ISRC',
        "ASF": 'WM/ISRC',
        "RIFF": None,
    },
    'itunes_cddb_1': {
        "name": 'iTunes CDDB 1 [9]',
        "ID3v2": 'iTunes_CDDB_1',
        "Vorbis": None,
        "APEv2": None,
        "iTunes": '----:com.apple.iTunes:iTunes_CDDB_1',
        "ASF": None,
        "RIFF": None,
    },
    'key': {
        "name": 'Initial Key',
        "ID3v2": 'TKEY',
        "Vorbis": 'KEY',
        "APEv2": 'Key',
        "iTunes": '----:com.apple.iTunes:initialkey',
        "ASF": 'WM/InitialKey',
        "RIFF": None,
    },
    'key (Picard>=1.4)': {
        "name": 'Initial Key',
        "ID3v2": 'TKEY',
        "Vorbis": 'KEY',
        "APEv2": 'Key',
        "iTunes": '----:com.apple.iTunes:initialkey',
        "ASF": 'WM/InitialKey',
        "RIFF": None,
    },
    'label': {
        "name": 'Record Label',
        "ID3v2": 'TPUB',
        "Vorbis": 'LABEL',
        "APEv2": 'Label',
        "iTunes": '----:com.apple.iTunes:LABEL',
        "ASF": 'WM/Publisher',
        "RIFF": None,
    },
    'language': {
        "name": 'Language',
        "ID3v2": 'TLAN',
        "Vorbis": 'LANGUAGE',
        "APEv2": 'Language',
        "iTunes": '----:com.apple.iTunes:LANGUAGE',
        "ASF": 'WM/Language',
        "RIFF": 'ILNG',
    },
    'license': {
        "name": 'License [6] [7]',
        "ID3v2": 'WCOP (single URL)\nTXXX:LICENSE (multiple or non-URL)',
        "Vorbis": 'LICENSE',
        "APEv2": 'License',
        "iTunes": '----:com.apple.iTunes:LICENSE',
        "ASF": None,
        "RIFF": None,
    },
    'lyricist': {
        "name": 'Lyricist',
        "ID3v2": 'TEXT',
        "Vorbis": 'LYRICIST',
        "APEv2": 'Lyricist',
        "iTunes": '----:com.apple.iTunes:LYRICIST',
        "ASF": 'WM/Writer',
        "RIFF": None,
    },
    'lyrics:description': {
        "name": 'Lyrics [4]',
        "ID3v2": 'USLT:description',
        "Vorbis": 'LYRICS',
        "APEv2": 'Lyrics',
        "iTunes": '©lyr',
        "ASF": 'WM/Lyrics',
        "RIFF": None,
    },
    'media': {
        "name": 'Media',
        "ID3v2": 'TMED',
        "Vorbis": 'MEDIA',
        "APEv2": 'Media',
        "iTunes": '----:com.apple.iTunes:MEDIA',
        "ASF": 'WM/Media',
        "RIFF": 'IMED',
    },
    'mixer': {
        "name": 'Mixer',
        "ID3v2": 'TIPL:mix (ID3v2.4)\nIPLS:mix (ID3v2.3)',
        "Vorbis": 'MIXER',
        "APEv2": 'Mixer',
        "iTunes": '----:com.apple.iTunes:MIXER',
        "ASF": 'WM/Mixer',
        "RIFF": None,
    },
    'mood': {
        "name": 'Mood [3]',
        "ID3v2": 'TMOO (ID3v2.4 only)',
        "Vorbis": 'MOOD',
        "APEv2": 'Mood',
        "iTunes": '----:com.apple.iTunes:MOOD',
        "ASF": 'WM/Mood',
        "RIFF": None,
    },
    'movement (Picard>=2.1)': {
        "name": 'Movement [4]',
        "ID3v2": 'MVNM',
        "Vorbis": 'MOVEMENTNAME',
        "APEv2": 'MOVEMENTNAME',
        "iTunes": '©mvn',
        "ASF": None,
        "RIFF": None,
    },
    'movementnumber (Picard>=2.1)': {
        "name": 'Movement Number [4]',
        "ID3v2": 'MVIN',
        "Vorbis": 'MOVEMENT',
        "APEv2": 'MOVEMENT',
        "iTunes": 'mvi',
        "ASF": None,
        "RIFF": None,
    },
    'movementtotal (Picard>=2.1)': {
        "name": 'Movement Count [4]',
        "ID3v2": 'MVIN',
        "Vorbis": 'MOVEMENTTOTAL',
        "APEv2": 'MOVEMENTTOTAL',
        "iTunes": 'mvc',
        "ASF": None,
        "RIFF": None,
    },
    'musicbrainz_albumartistid': {
        "name": 'MusicBrainz Release Artist ID',
        "ID3v2": 'TXXX:MusicBrainz Album Artist Id',
        "Vorbis": 'MUSICBRAINZ_ALBUMARTISTID',
        "APEv2": 'Musicbrainz_Albumartistid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Album Artist Id',
        "ASF": 'MusicBrainz/Album Artist Id',
        "RIFF": None,
    },
    'musicbrainz_albumid': {
        "name": 'MusicBrainz Release ID',
        "ID3v2": 'TXXX:MusicBrainz Album Id',
        "Vorbis": 'MUSICBRAINZ_ALBUMID',
        "APEv2": 'Musicbrainz_Albumid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Album Id',
        "ASF": 'MusicBrainz/Album Id',
        "RIFF": None,
    },
    'musicbrainz_artistid': {
        "name": 'MusicBrainz Artist ID',
        "ID3v2": 'TXXX:MusicBrainz Artist Id',
        "Vorbis": 'MUSICBRAINZ_ARTISTID',
        "APEv2": 'Musicbrainz_Artistid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Artist Id',
        "ASF": 'MusicBrainz/Artist Id',
        "RIFF": None,
    },
    'musicbrainz_composerid': {
        "name": 'MusicBrainz Composer ID',
        "ID3v2": 'TXXX:MusicBrainz Composer Id',
        "Vorbis": 'MUSICBRAINZ_COMPOSERID',
        "APEv2": 'Musicbrainz_Composerid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Composer Id',
        "ASF": 'MusicBrainz/Composer Id',
        "RIFF": None,
    },
    'musicbrainz_discid': {
        "name": 'MusicBrainz Disc ID',
        "ID3v2": 'TXXX:MusicBrainz Disc Id',
        "Vorbis": 'MUSICBRAINZ_DISCID',
        "APEv2": 'Musicbrainz_Discid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Disc Id',
        "ASF": 'MusicBrainz/Disc Id',
        "RIFF": None,
    },
    'musicbrainz_originalalbumid': {
        "name": 'MusicBrainz Original Release ID',
        "ID3v2": 'TXXX:MusicBrainz Original Album Id',
        "Vorbis": 'MUSICBRAINZ_ORIGINALALBUMID',
        "APEv2": None,
        "iTunes": '----:com.apple.iTunes:MusicBrainz Original Album Id (Picard>=2.1)',
        "ASF": 'MusicBrainz/Original Album Id (Picard>=2.1)',
        "RIFF": None,
    },
    'musicbrainz_originalartistid': {
        "name": 'MusicBrainz Original Artist ID',
        "ID3v2": 'TXXX:MusicBrainz Original Artist Id',
        "Vorbis": 'MUSICBRAINZ_ORIGINALARTISTID',
        "APEv2": None,
        "iTunes": '----:com.apple.iTunes:MusicBrainz Original Artist Id (Picard>=2.1)',
        "ASF": 'MusicBrainz/Original Artist Id (Picard>=2.1)',
        "RIFF": None,
    },
    'musicbrainz_recordingid': {
        "name": 'MusicBrainz Recording ID',
        "ID3v2": 'UFID:http://musicbrainz.org',
        "Vorbis": 'MUSICBRAINZ_TRACKID',
        "APEv2": 'musicbrainz_trackid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Track Id',
        "ASF": 'MusicBrainz/Track Id',
        "RIFF": None,
    },
    'musicbrainz_releasegroupid': {
        "name": 'MusicBrainz Release Group ID',
        "ID3v2": 'TXXX:MusicBrainz Release Group Id',
        "Vorbis": 'MUSICBRAINZ_RELEASEGROUPID',
        "APEv2": 'Musicbrainz_Releasegroupid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Release Group Id',
        "ASF": 'MusicBrainz/Release Group Id',
        "RIFF": None,
    },
    'musicbrainz_trackid': {
        "name": 'MusicBrainz Track ID',
        "ID3v2": 'TXXX:MusicBrainz Release Track Id',
        "Vorbis": 'MUSICBRAINZ_RELEASETRACKID',
        "APEv2": 'musicbrainz_releasetrackid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Release Track Id',
        "ASF": 'MusicBrainz/Release Track Id',
        "RIFF": None,
    },
    'musicbrainz_trmid (deprecated)': {
        "name": 'MusicBrainz TRM ID',
        "ID3v2": 'TXXX:MusicBrainz TRM Id',
        "Vorbis": 'MUSICBRAINZ_TRMID',
        "APEv2": 'MUSICBRAINZ_TRMID',
        "iTunes": '----:com.apple.iTunes:MusicBrainz TRM Id',
        "ASF": 'MusicBrainz/TRM Id',
        "RIFF": None,
    },
    'musicbrainz_workid': {
        "name": 'MusicBrainz Work ID',
        "ID3v2": 'TXXX:MusicBrainz Work Id',
        "Vorbis": 'MUSICBRAINZ_WORKID',
        "APEv2": 'Musicbrainz_Workid',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Work Id',
        "ASF": 'MusicBrainz/Work Id',
        "RIFF": None,
    },
    'musicip_fingerprint': {
        "name": 'MusicIP Fingerprint',
        "ID3v2": 'TXXX:MusicMagic Fingerprint',
        "Vorbis": 'FINGERPRINT=MusicMagic Fingerprint {fingerprint}',
        "APEv2": None,
        "iTunes": '----:com.apple.iTunes:fingerprint',
        "ASF": None,
        "RIFF": None,
    },
    'musicip_puid': {
        "name": 'MusicIP PUID',
        "ID3v2": 'TXXX:MusicIP PUID',
        "Vorbis": 'MUSICIP_PUID',
        "APEv2": 'Musicip_Puid',
        "iTunes": '----:com.apple.iTunes:MusicIP PUID',
        "ASF": 'MusicIP/PUID',
        "RIFF": None,
    },
    'originalalbum': {
        "name": 'Original Album',
        "ID3v2": 'TOAL',
        "Vorbis": None,
        "APEv2": None,
        "iTunes": None,
        "ASF": 'WM/OriginalAlbumTitle (Picard>=2.1)',
        "RIFF": None,
    },
    'originalartist': {
        "name": 'Original Artist',
        "ID3v2": 'TOPE',
        "Vorbis": None,
        "APEv2": 'Original Artist (Picard>=2.1)',
        "iTunes": None,
        "ASF": 'WM/OriginalArtist (Picard>=2.1)',
        "RIFF": None,
    },
    'originaldate': {
        "name": 'Original Release Date [1]',
        "ID3v2": 'TDOR (ID3v2.4)\nTORY (ID3v2.3)',
        "Vorbis": 'ORIGINALDATE',
        "APEv2": None,
        "iTunes": None,
        "ASF": 'WM/OriginalReleaseTime (Picard>=1.3.1)\nWM/OriginalReleaseYear (Picard<=1.3.0)',
        "RIFF": None,
    },
    'originalfilename (Picard>=2.3)': {
        "name": 'Original Filename',
        "ID3v2": 'TOFN',
        "Vorbis": 'ORIGINALFILENAME',
        "APEv2": 'Originalfilename',
        "iTunes": None,
        "ASF": 'WM/OriginalFilename',
        "RIFF": None,
    },
    'originalyear': {
        "name": 'Original Release Year [1]',
        "ID3v2": None,
        "Vorbis": 'ORIGINALYEAR',
        "APEv2": 'Originalyear',
        "iTunes": None,
        "ASF": 'WM/OriginalReleaseYear (Picard>=1.3.1)',
        "RIFF": None,
    },
    'performer:instrument': {
        "name": 'Performer',
        "ID3v2": 'TMCL:instrument (ID3v2.4)\nIPLS:instrument (ID3v2.3)',
        "Vorbis": 'PERFORMER={artist} (instrument)',
        "APEv2": 'Performer',
        "iTunes": None,
        "ASF": None,
        "RIFF": None,
    },
    'podcast': {
        "name": 'Podcast [4]',
        "ID3v2": None,
        "Vorbis": None,
        "APEv2": None,
        "iTunes": 'pcst',
        "ASF": None,
        "RIFF": None,
    },
    'podcasturl': {
        "name": 'Podcast URL [4]',
        "ID3v2": None,
        "Vorbis": None,
        "APEv2": None,
        "iTunes": 'purl',
        "ASF": None,
        "RIFF": None,
    },
    'producer': {
        "name": 'Producer',
        "ID3v2": 'TIPL:producer (ID3v2.4)\nIPLS:producer (ID3v2.3)',
        "Vorbis": 'PRODUCER',
        "APEv2": 'Producer',
        "iTunes": '----:com.apple.iTunes:PRODUCER',
        "ASF": 'WM/Producer',
        "RIFF": 'IPRO',
    },
    'releasecountry': {
        "name": 'Release Country',
        "ID3v2": 'TXXX:MusicBrainz Album Release Country',
        "Vorbis": 'RELEASECOUNTRY',
        "APEv2": 'Releasecountry',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Album Release Country',
        "ASF": 'MusicBrainz/Album Release Country',
        "RIFF": 'ICNT',
    },
    'releasestatus': {
        "name": 'Release Status',
        "ID3v2": 'TXXX:MusicBrainz Album Status',
        "Vorbis": 'RELEASESTATUS',
        "APEv2": 'MUSICBRAINZ_ALBUMSTATUS',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Album Status',
        "ASF": 'MusicBrainz/Album Status',
        "RIFF": None,
    },
    'releasetype': {
        "name": 'Release Type',
        "ID3v2": 'TXXX:MusicBrainz Album Type',
        "Vorbis": 'RELEASETYPE',
        "APEv2": 'MUSICBRAINZ_ALBUMTYPE',
        "iTunes": '----:com.apple.iTunes:MusicBrainz Album Type',
        "ASF": 'MusicBrainz/Album Type',
        "RIFF": None,
    },
    'remixer': {
        "name": 'Remixer',
        "ID3v2": 'TPE4',
        "Vorbis": 'REMIXER',
        "APEv2": 'MixArtist',
        "iTunes": '----:com.apple.iTunes:REMIXER',
        "ASF": 'WM/ModifiedBy',
        "RIFF": None,
    },
    'replaygain_album_gain (Picard>=2.2)': {
        "name": 'ReplayGain Album Gain',
        "ID3v2": 'TXXX:REPLAYGAIN_ALBUM_GAIN',
        "Vorbis": 'REPLAYGAIN_ALBUM_GAIN',
        "APEv2": 'REPLAYGAIN_ALBUM_GAIN',
        "iTunes": '----:com.apple.iTunes:REPLAYGAIN_ALBUM_GAIN',
        "ASF": 'REPLAYGAIN_ALBUM_GAIN',
        "RIFF": None,
    },
    'replaygain_album_peak (Picard>=2.2)': {
        "name": 'ReplayGain Album Peak',
        "ID3v2": 'TXXX:REPLAYGAIN_ALBUM_PEAK',
        "Vorbis": 'REPLAYGAIN_ALBUM_PEAK',
        "APEv2": 'REPLAYGAIN_ALBUM_PEAK',
        "iTunes": '----:com.apple.iTunes:REPLAYGAIN_ALBUM_PEAK',
        "ASF": 'REPLAYGAIN_ALBUM_PEAK',
        "RIFF": None,
    },
    'replaygain_album_range (Picard>=2.2)': {
        "name": 'ReplayGain Album Range',
        "ID3v2": 'TXXX:REPLAYGAIN_ALBUM_RANGE',
        "Vorbis": 'REPLAYGAIN_ALBUM_RANGE',
        "APEv2": 'REPLAYGAIN_ALBUM_RANGE',
        "iTunes": '----:com.apple.iTunes:REPLAYGAIN_ALBUM_RANGE',
        "ASF": 'REPLAYGAIN_ALBUM_RANGE',
        "RIFF": None,
    },
    'replaygain_reference_loudness (Picard>=2.2)': {
        "name": 'ReplayGain Reference Loudness',
        "ID3v2": 'TXXX:REPLAYGAIN_REFERENCE_LOUDNESS',
        "Vorbis": 'REPLAYGAIN_REFERENCE_LOUDNESS',
        "APEv2": 'REPLAYGAIN_REFERENCE_LOUDNESS',
        "iTunes": '----:com.apple.iTunes:REPLAYGAIN_REFERENCE_LOUDNESS',
        "ASF": 'REPLAYGAIN_REFERENCE_LOUDNESS',
        "RIFF": None,
    },
    'replaygain_track_gain (Picard>=2.2)': {
        "name": 'ReplayGain Track Gain',
        "ID3v2": 'TXXX:REPLAYGAIN_TRACK_GAIN',
        "Vorbis": 'REPLAYGAIN_TRACK_GAIN',
        "APEv2": 'REPLAYGAIN_TRACK_GAIN',
        "iTunes": '----:com.apple.iTunes:REPLAYGAIN_TRACK_GAIN',
        "ASF": 'REPLAYGAIN_TRACK_GAIN',
        "RIFF": None,
    },
    'replaygain_track_peak (Picard>=2.2)': {
        "name": 'ReplayGain Track Peak',
        "ID3v2": 'TXXX:REPLAYGAIN_TRACK_PEAK',
        "Vorbis": 'REPLAYGAIN_TRACK_PEAK',
        "APEv2": 'REPLAYGAIN_TRACK_PEAK',
        "iTunes": '----:com.apple.iTunes:REPLAYGAIN_TRACK_PEAK',
        "ASF": 'REPLAYGAIN_TRACK_PEAK',
        "RIFF": None,
    },
    'replaygain_track_range (Picard>=2.2)': {
        "name": 'ReplayGain Track Range',
        "ID3v2": 'TXXX:REPLAYGAIN_TRACK_RANGE',
        "Vorbis": 'REPLAYGAIN_TRACK_RANGE',
        "APEv2": 'REPLAYGAIN_TRACK_RANGE',
        "iTunes": '----:com.apple.iTunes:REPLAYGAIN_TRACK_RANGE',
        "ASF": 'REPLAYGAIN_TRACK_RANGE',
        "RIFF": None,
    },
    'script': {
        "name": 'Script',
        "ID3v2": 'TXXX:SCRIPT',
        "Vorbis": 'SCRIPT',
        "APEv2": 'Script',
        "iTunes": '----:com.apple.iTunes:SCRIPT',
        "ASF": 'WM/Script',
        "RIFF": None,
    },
    'show': {
        "name": 'Show Name [4]',
        "ID3v2": None,
        "Vorbis": None,
        "APEv2": None,
        "iTunes": 'tvsh',
        "ASF": None,
        "RIFF": None,
    },
    'showmovement (Picard>=2.1)': {
        "name": 'Show Work & Movement [4]',
        "ID3v2": 'TXXX:SHOWMOVEMENT',
        "Vorbis": 'SHOWMOVEMENT',
        "APEv2": 'SHOWMOVEMENT',
        "iTunes": 'shwm',
        "ASF": None,
        "RIFF": None,
    },
    'showsort': {
        "name": 'Show Name Sort Order [4]',
        "ID3v2": None,
        "Vorbis": None,
        "APEv2": None,
        "iTunes": 'sosn',
        "ASF": None,
        "RIFF": None,
    },
    'subtitle': {
        "name": 'Subtitle [4]',
        "ID3v2": 'TIT3',
        "Vorbis": 'SUBTITLE',
        "APEv2": 'Subtitle',
        "iTunes": '----:com.apple.iTunes:SUBTITLE',
        "ASF": 'WM/SubTitle',
        "RIFF": None,
    },
    'syncedlyrics:language:description': {
        "name": 'Synced Lyrics',
        "ID3v2": 'SYLT:description',
        "Vorbis": None,
        "APEv2": None,
        "iTunes": None,
        "ASF": 'WM/Lyrics_Synchronised',
        "RIFF": None,
    },
    'tcop': {
        "name": 'Copyright [4]',
        "ID3v2": 'TCOP',
        "Vorbis": 'COPYRIGHT',
        "APEv2": 'Copyright',
        "iTunes": 'cprt',
        "ASF": 'Copyright',
        "RIFF": 'ICOP',
    },
    'title': {
        "name": 'Track Title',
        "ID3v2": 'TIT2',
        "Vorbis": 'TITLE',
        "APEv2": 'Title',
        "iTunes": '©nam',
        "ASF": 'Title',
        "RIFF": 'INAM',
    },
    'titlesort': {
        "name": 'Track Title Sort Order [4]',
        "ID3v2": 'TSOT',
        "Vorbis": 'TITLESORT',
        "APEv2": 'Titlesort',
        "iTunes": 'sonm',
        "ASF": 'WM/TitleSortOrder',
        "RIFF": None,
    },
    'totaldiscs': {
        "name": 'Total Discs',
        "ID3v2": 'TPOS',
        "Vorbis": 'DISCTOTAL and TOTALDISCS',
        "APEv2": 'Disc',
        "iTunes": 'disk',
        "ASF": 'WM/PartOfSet (Picard>=1.3.1)',
        "RIFF": None,
    },
    'totaltracks': {
        "name": 'Total Tracks',
        "ID3v2": 'TRCK',
        "Vorbis": 'TRACKTOTAL and TOTALTRACKS',
        "APEv2": 'Track',
        "iTunes": 'trkn',
        "ASF": None,
        "RIFF": None,
    },
    'tracknumber': {
        "name": 'Track Number',
        "ID3v2": 'TRCK',
        "Vorbis": 'TRACKNUMBER',
        "APEv2": 'Track',
        "iTunes": 'trkn',
        "ASF": 'WM/TrackNumber',
        "RIFF": 'ITRK',
    },
    'website': {
        "name": 'Website (official artist website)',
        "ID3v2": 'WOAR',
        "Vorbis": 'WEBSITE',
        "APEv2": 'Weblink',
        "iTunes": None,
        "ASF": 'WM/AuthorURL (Picard>=1.3.1)',
        "RIFF": None,
    },
    'work (Picard>=1.3)': {
        "name": 'Work Title',
        "ID3v2": 'TXXX:WORK TIT1 [8]',
        "Vorbis": 'WORK',
        "APEv2": 'Work',
        "iTunes": '©wrk (Picard>=2.1)',
        "ASF": 'WM/Work',
        "RIFF": None,
    },
    'writer': {
        "name": 'Writer [2]',
        "ID3v2": 'TXXX:Writer (Picard>=1.3)',
        "Vorbis": 'WRITER',
        "APEv2": 'Writer',
        "iTunes": None,
        "ASF": None,
        "RIFF": 'IWRI',
    },
}
